name: Schedule Script Execution

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

  schedule:

    - cron: "14 18 * * 5"  # Run every Sunday at 11 AM UTC

jobs:

  run-script:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository

        uses: actions/checkout@v2

      - name: Set up PowerShell

        uses: microsoft/setup-powershell@v1

      - name: Run PowerShell script

        run: |

          pwsh -File Export-sp-list-items.ps1 -SiteUrl ${{ secrets.SITE_URL }} -Username ${{ secrets.USER_NAME }} -Password ${{ secrets.PASSWORD }} -ListName " Issues List" -FieldInternalName "Status" -FieldValue "Closed" -FolderPath "Shared Documents/automated export files"

